# change the followings to match your Github username and repo name
baseurl: "/" # the name of your github repo
url: "https://iokarkan.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "iokarkan's Blogfolio"
description: Blog-Portfolio | Github Pages-Jekyll-TailwindCSS

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Ioannis Karkanias
author-bio: ML / AI / Data Science | Particle Physics PhD  # change to false to hide
author-image: iokarkan.jpg  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About me
  permalink: about
- text: My work
  permalink: portfolio
- text: My blog
  permalink: blog

# use false to turn off any social media links
twitter: false
facebook: false
instagram: false
github: false
linkedin: https://www.linkedin.com/in/ioannis-karkanias-71996a1aa/
medium: false
google-scholar: false
email: mailto:ioannis.karkanias@gmail.com

# footer information
footer-msg: "Hosted by Github (Credits to H. Wang)"
footer-msg-link: https://github.com/iokarkan/blogfolio

# google analytics
# google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
